-- Truncate and load test
-- Create the table
CREATE OR REPLACE TABLE titanic AS
SELECT * FROM titanic_before;

-- Truncate it
TRUNCATE titanic;

-- Load the exact same data again
INSERT INTO titanic
SELECT * FROM titanic_before;

-- See the files
SELECT 
T.TABLE_CATALOG,
T.TABLE_SCHEMA,
T.TABLE_NAME,
T.IS_TRANSIENT,
T.ROW_COUNT,
T.BYTES,
T.RETENTION_TIME,
T.CREATED,
T.LAST_ALTERED,
TSM.ACTIVE_BYTES,
TSM.TIME_TRAVEL_BYTES,
TSM.FAILSAFE_BYTES

FROM INFORMATION_SCHEMA.TABLES T
INNER JOIN INFORMATION_SCHEMA.TABLE_STORAGE_METRICS TSM
ON T.TABLE_CATALOG=TSM.TABLE_CATALOG
AND T.TABLE_SCHEMA=TSM.TABLE_SCHEMA
AND T.TABLE_NAME=TSM.TABLE_NAME
WHERE T.TABLE_NAME = 'TITANIC' AND TABLE_DROPPED is null
;
